name: Build and push to Docker Hub

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout infra repo (Dockerfile)
        uses: actions/checkout@v4

      - name: Checkout Flask app repo
        uses: actions/checkout@v4
        with:
          repository: fbalint2001/flask-app
          token: ${{ secrets.GITHUB_TOKEN }}
          path: flask-app

      - name: Copy app into build context
        run: |
          cp -r flask-app/* .

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/flask-app:latest
